version: '3.9'

services:
  # Development Service
  dev:
    build:
      context: .
      # target: dev
      dockerfile: Dockerfile
    container_name: front-dev-container
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - frontend
    env_file:
      - .env
    volumes:  
      - type: bind
        source: ./
        target: /app
        
networks:
  frontend:
