version: '3.9'

services:
  dev:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: front-dev-container
    restart: unless-stopped
    ports:
      - '80:5173'
    networks:
      - frontend
    env_file:
      - .env
    volumes:
      - ./:/app

  preview:
    build:
      context: .
      target: preview
      dockerfile: Dockerfile
    container_name: front-preview-container
    restart: unless-stopped
    ports:
      - '83:4173'
    networks:
      - frontend
    env_file:
      - .env
    # volumes:
    #   - ./:/app

networks:
  frontend:
